import type { ItemCategory, Rarity } from './types';

export interface CatalogItem {
  name: string;
  /** Purchase cost per unit in GP (1 CP = 0.01, 1 SP = 0.1, 1 EP = 0.5, 1 PP = 10). */
  cost: number;
  /** Auto-filled on pick for rarity-bearing categories (consumables). */
  rarity?: Rarity;
  /** Dropdown section heading (rendered as an <optgroup> in the item-name picker). */
  group?: string;
}

/** Tag every item in a dropdown section with its heading. */
function section(group: string, items: Omit<CatalogItem, 'group'>[]): CatalogItem[] {
  return items.map((item) => ({ ...item, group }));
}

/**
 * Hardcoded common items offered in the item-name dropdown when gaining an item.
 * Picking one auto-fills its rarity, and (in a purchase log) its cost; users can
 * always switch to manual input for anything not listed.
 *
 * Equipment = 2024 PHB weapons + armor tables. Consumables = the potions/oils the
 * owner allows for purchase. Categories without an entry here (magic items,
 * blessings, …) get a plain text input, since those are too varied to enumerate.
 */
export const ITEM_CATALOG: Partial<Record<ItemCategory, CatalogItem[]>> = {
  equipment: [
    ...section('Simple Melee Weapons', [
      { name: 'Club', cost: 0.1 },
      { name: 'Dagger', cost: 2 },
      { name: 'Greatclub', cost: 0.2 },
      { name: 'Handaxe', cost: 5 },
      { name: 'Javelin', cost: 0.5 },
      { name: 'Light Hammer', cost: 2 },
      { name: 'Mace', cost: 5 },
      { name: 'Quarterstaff', cost: 0.2 },
      { name: 'Sickle', cost: 1 },
      { name: 'Spear', cost: 1 },
    ]),
    ...section('Simple Ranged Weapons', [
      { name: 'Dart', cost: 0.05 },
      { name: 'Light Crossbow', cost: 25 },
      { name: 'Shortbow', cost: 25 },
      { name: 'Sling', cost: 0.1 },
    ]),
    ...section('Martial Melee Weapons', [
      { name: 'Battleaxe', cost: 10 },
      { name: 'Flail', cost: 10 },
      { name: 'Glaive', cost: 20 },
      { name: 'Greataxe', cost: 30 },
      { name: 'Greatsword', cost: 50 },
      { name: 'Halberd', cost: 20 },
      { name: 'Lance', cost: 10 },
      { name: 'Longsword', cost: 15 },
      { name: 'Maul', cost: 10 },
      { name: 'Morningstar', cost: 15 },
      { name: 'Pike', cost: 5 },
      { name: 'Rapier', cost: 25 },
      { name: 'Scimitar', cost: 25 },
      { name: 'Shortsword', cost: 10 },
      { name: 'Trident', cost: 5 },
      { name: 'Warhammer', cost: 15 },
      { name: 'War Pick', cost: 5 },
      { name: 'Whip', cost: 2 },
    ]),
    ...section('Martial Ranged Weapons', [
      { name: 'Blowgun', cost: 10 },
      { name: 'Hand Crossbow', cost: 75 },
      { name: 'Heavy Crossbow', cost: 50 },
      { name: 'Longbow', cost: 50 },
    ]),
    ...section('Light Armor', [
      { name: 'Padded Armor', cost: 5 },
      { name: 'Leather Armor', cost: 10 },
      { name: 'Studded Leather Armor', cost: 45 },
    ]),
    ...section('Medium Armor', [
      { name: 'Hide Armor', cost: 10 },
      { name: 'Chain Shirt', cost: 50 },
      { name: 'Scale Mail', cost: 50 },
      { name: 'Breastplate', cost: 400 },
      { name: 'Half Plate Armor', cost: 750 },
    ]),
    ...section('Heavy Armor', [
      { name: 'Ring Mail', cost: 30 },
      { name: 'Chain Mail', cost: 75 },
      { name: 'Splint Armor', cost: 200 },
      { name: 'Plate Armor', cost: 1500 },
    ]),
    ...section('Shield', [{ name: 'Shield', cost: 10 }]),
    ...section('Artisan’s Tools', [
      { name: 'Alchemist’s Supplies', cost: 50 },
      { name: 'Brewer’s Supplies', cost: 20 },
      { name: 'Calligrapher’s Supplies', cost: 10 },
      { name: 'Carpenter’s Tools', cost: 8 },
      { name: 'Cartographer’s Tools', cost: 15 },
      { name: 'Cobbler’s Tools', cost: 5 },
      { name: 'Cook’s Utensils', cost: 1 },
      { name: 'Glassblower’s Tools', cost: 30 },
      { name: 'Jeweler’s Tools', cost: 25 },
      { name: 'Leatherworker’s Tools', cost: 5 },
      { name: 'Mason’s Tools', cost: 10 },
      { name: 'Painter’s Supplies', cost: 10 },
      { name: 'Potter’s Tools', cost: 10 },
      { name: 'Smith’s Tools', cost: 20 },
      { name: 'Tinker’s Tools', cost: 50 },
      { name: 'Weaver’s Tools', cost: 1 },
      { name: 'Woodcarver’s Tools', cost: 1 },
    ]),
    // Gaming Set and Musical Instrument have per-variant prices, so each variant
    // is its own entry (a self-describing name beats a bare "Dice" in the inventory).
    ...section('Other Tools', [
      { name: 'Disguise Kit', cost: 25 },
      { name: 'Forgery Kit', cost: 15 },
      { name: 'Gaming Set (Dice)', cost: 0.1 },
      { name: 'Gaming Set (Dragonchess)', cost: 1 },
      { name: 'Gaming Set (Playing Cards)', cost: 0.5 },
      { name: 'Gaming Set (Three-Dragon Ante)', cost: 1 },
      { name: 'Herbalism Kit', cost: 5 },
      { name: 'Musical Instrument (Bagpipes)', cost: 30 },
      { name: 'Musical Instrument (Drum)', cost: 6 },
      { name: 'Musical Instrument (Dulcimer)', cost: 25 },
      { name: 'Musical Instrument (Flute)', cost: 2 },
      { name: 'Musical Instrument (Horn)', cost: 3 },
      { name: 'Musical Instrument (Lute)', cost: 35 },
      { name: 'Musical Instrument (Lyre)', cost: 30 },
      { name: 'Musical Instrument (Pan Flute)', cost: 12 },
      { name: 'Musical Instrument (Shawm)', cost: 2 },
      { name: 'Musical Instrument (Viol)', cost: 30 },
      { name: 'Navigator’s Tools', cost: 25 },
      { name: 'Poisoner’s Kit', cost: 50 },
      { name: 'Thieves’ Tools', cost: 25 },
    ]),
    // Comma-inverted PHB table names ("Lantern, Bullseye") are naturalized the way the
    // PHB's own prose writes them, and the list re-alphabetized by the natural name.
    // Deliberately absent: Ammunition, Arcane/Druidic Focus and Holy Symbol (cost
    // "Varies" — no single price to auto-fill), and Potion of Healing (already a
    // consumable; a second equipment entry would create a separate stack).
    ...section('Adventuring Gear', [
      { name: 'Acid', cost: 25 },
      { name: 'Alchemist’s Fire', cost: 50 },
      { name: 'Antitoxin', cost: 50 },
      { name: 'Backpack', cost: 2 },
      { name: 'Ball Bearings', cost: 1 },
      { name: 'Barrel', cost: 2 },
      { name: 'Basic Poison', cost: 100 },
      { name: 'Basket', cost: 0.4 },
      { name: 'Bedroll', cost: 1 },
      { name: 'Bell', cost: 1 },
      { name: 'Blanket', cost: 0.5 },
      { name: 'Block and Tackle', cost: 1 },
      { name: 'Book', cost: 25 },
      { name: 'Bucket', cost: 0.05 },
      { name: 'Bullseye Lantern', cost: 10 },
      { name: 'Burglar’s Pack', cost: 16 },
      { name: 'Caltrops', cost: 1 },
      { name: 'Candle', cost: 0.01 },
      { name: 'Chain', cost: 5 },
      { name: 'Chest', cost: 5 },
      { name: 'Climber’s Kit', cost: 25 },
      { name: 'Component Pouch', cost: 25 },
      { name: 'Costume', cost: 5 },
      { name: 'Crossbow Bolt Case', cost: 1 },
      { name: 'Crowbar', cost: 2 },
      { name: 'Diplomat’s Pack', cost: 39 },
      { name: 'Dungeoneer’s Pack', cost: 12 },
      { name: 'Entertainer’s Pack', cost: 40 },
      { name: 'Explorer’s Pack', cost: 10 },
      { name: 'Fine Clothes', cost: 15 },
      { name: 'Flask', cost: 0.02 },
      { name: 'Glass Bottle', cost: 2 },
      { name: 'Grappling Hook', cost: 2 },
      { name: 'Healer’s Kit', cost: 5 },
      { name: 'Holy Water', cost: 25 },
      { name: 'Hooded Lantern', cost: 5 },
      { name: 'Hunting Trap', cost: 5 },
      { name: 'Ink', cost: 10 },
      { name: 'Ink Pen', cost: 0.02 },
      { name: 'Iron Pot', cost: 2 },
      { name: 'Iron Spikes', cost: 1 },
      { name: 'Jug', cost: 0.02 },
      { name: 'Ladder', cost: 0.1 },
      { name: 'Lamp', cost: 0.5 },
      { name: 'Lock', cost: 10 },
      { name: 'Magnifying Glass', cost: 100 },
      { name: 'Manacles', cost: 2 },
      { name: 'Map', cost: 1 },
      { name: 'Map or Scroll Case', cost: 1 },
      { name: 'Mirror', cost: 5 },
      { name: 'Net', cost: 1 },
      { name: 'Oil', cost: 0.1 },
      { name: 'Paper', cost: 0.2 },
      { name: 'Parchment', cost: 0.1 },
      { name: 'Perfume', cost: 5 },
      { name: 'Pole', cost: 0.05 },
      { name: 'Portable Ram', cost: 4 },
      { name: 'Pouch', cost: 0.5 },
      { name: 'Priest’s Pack', cost: 33 },
      { name: 'Quiver', cost: 1 },
      { name: 'Rations', cost: 0.5 },
      { name: 'Robe', cost: 1 },
      { name: 'Rope', cost: 1 },
      { name: 'Sack', cost: 0.01 },
      { name: 'Scholar’s Pack', cost: 40 },
      { name: 'Shovel', cost: 2 },
      { name: 'Signal Whistle', cost: 0.05 },
      { name: 'Spell Scroll (Cantrip)', cost: 30 },
      { name: 'Spell Scroll (Level 1)', cost: 50 },
      { name: 'Spyglass', cost: 1000 },
      { name: 'String', cost: 0.1 },
      { name: 'Tent', cost: 2 },
      { name: 'Tinderbox', cost: 0.5 },
      { name: 'Torch', cost: 0.01 },
      { name: 'Traveler’s Clothes', cost: 2 },
      { name: 'Vial', cost: 1 },
      { name: 'Waterskin', cost: 0.2 },
    ]),
    ...section('Mounts and Other Animals', [
      { name: 'Camel', cost: 50 },
      { name: 'Draft Horse', cost: 50 },
      { name: 'Elephant', cost: 200 },
      { name: 'Mastiff', cost: 25 },
      { name: 'Mule', cost: 8 },
      { name: 'Pony', cost: 30 },
      { name: 'Riding Horse', cost: 75 },
      { name: 'Warhorse', cost: 400 },
    ]),
  ],
  // Costs are the AL standard by-rarity prices for consumables (half the DMG
  // magic item value): common 50, uncommon 200, rare 2,000, very rare 20,000,
  // legendary 100,000.
  consumable: [
    ...section('Common', [
      { name: 'Potion of Climbing', cost: 50, rarity: 'common' },
      { name: 'Potion of Comprehension', cost: 50, rarity: 'common' },
      { name: 'Potion of Healing', cost: 50, rarity: 'common' },
    ]),
    ...section('Uncommon', [
      { name: 'Oil of Slipperiness', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Animal Friendship', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Fire Breath', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Growth', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Healing (Greater)', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Hill Giant Strength', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Poison', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Pugilism', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Resistance', cost: 200, rarity: 'uncommon' },
      { name: 'Potion of Water Breathing', cost: 200, rarity: 'uncommon' },
    ]),
    ...section('Rare', [
      { name: 'Elixir of Health', cost: 2000, rarity: 'rare' },
      { name: 'Oil of Etherealness', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Clairvoyance', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Diminution', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Fire Giant Strength', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Frost Giant Strength', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Gaseous Form', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Healing (Superior)', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Heroism', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Invisibility', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Invulnerability', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Mind Reading', cost: 2000, rarity: 'rare' },
      { name: 'Potion of Stone Giant Strength', cost: 2000, rarity: 'rare' },
    ]),
    ...section('Very Rare', [
      { name: 'Oil of Sharpness', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Cloud Giant Strength', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Flying', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Greater Invisibility', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Healing (Supreme)', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Longevity', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Speed', cost: 20000, rarity: 'very rare' },
      { name: 'Potion of Vitality', cost: 20000, rarity: 'very rare' },
    ]),
    ...section('Legendary', [
      { name: 'Potion of Storm Giant Strength', cost: 100000, rarity: 'legendary' },
    ]),
  ],
};
